repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-added-large-files
    args: [--maxkb=2000]
  - id: check-ast
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-toml
  - id: check-yaml
  - id: debug-statements
  - id: destroyed-symlinks
  - id: end-of-file-fixer
    files: \.(py|sh|rst|yml|yaml)$
  - id: mixed-line-ending
  - id: trailing-whitespace
    files: \.(py|sh|rst|yml|yaml)$
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.15.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
- repo: https://github.com/tox-dev/pyproject-fmt
  rev: v2.6.0
  hooks:
  - id: pyproject-fmt
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.9
  hooks:
  - id: ruff
    args: [--fix]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.17.1
  hooks:
  - id: mypy
    files: ^openapi_generator_cli/
    args: [--strict]
    additional_dependencies:
    - jdk4py
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.45.0
  hooks:
  - id: markdownlint
    exclude: ^.github/PULL_REQUEST_TEMPLATE.md
    args: [--disable=MD013]
