name: Test

on:
  push:
    branches:
    - master
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        - macos-latest
        python-version:
        - '3.10'
        - '3.13'
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: '21'
    - uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
        cache-dependency-glob: uv.lock
        python-version: ${{ matrix.python-version }}
    - name: Setup
      shell: bash
      run: |
        export DOWNLOAD_LATEST_ONLY=1
        uv run task publish
    - name: Test
      run: |
        uv run task test:ci
    - name: Pytest coverage comment
      if: ${{ github.actor != 'dependabot[bot]' }}
      uses: MishaKav/pytest-coverage-comment@v1.1.57
      with:
        pytest-xml-coverage-path: ./coverage.xml
        junitxml-path: ./pytest.xml
